books/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from .views import (
    BooksApiView,
)

urlpatterns = [
            path('api/', BooksApiView.as_view()),
            path('dashboard', views.dashboard, name='dashboard'),
            path('add_books', views.add_books),
            path('table_actions', views.table_actions),
            path('save_edit_made', views.save_edit_made),
            path('update_order_status', views.update_order_status),
            path('delete_book_item', views.delete_book_item),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

enasInventory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from enasInventory import views
from .views import LoginUserView
from django.contrib.auth.views import LogoutView 

from .middleware import login_exempt
from django.contrib.auth.decorators import login_required


urlpatterns = [
                  path("enas-inventory-admin/", admin.site.urls),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('login/', LoginUserView.as_view(), name='login'),
                  path('logout/', LogoutView.as_view(next_page='login'),name='logout'),
                  path('', views.index, name='index'),
                  path('add_account/', views.add_account_index, name='add_account'),
                  path('account_setup', views.account_setup, name='account_setup'),
                  # Other URL patterns
                  path('students/', include('students.urls')),
                  path('books/', include('books.urls')),
                  path('api-auth/', include('rest_framework.urls')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

student/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    # Other URL patterns
    path('add_students_bulk', views.add_students_bulk),
    path('add_student_entry', views.add_student_entry),
    path('edit_student_row', views.edit_student_row),
    path('update_paid_status', views.update_paid_status),
    path('update_all_paid', views.update_all_paid),
    path('students_book', views.student_books, name='students_book'),
    path('delete_student_row', views.delete_student_row),
    path('<int:pk>/', views.student_detail, name='student_detail'),
]

students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    # Other URL patterns
    path('add_students_bulk', views.add_students_bulk),
    path('add_student_entry', views.add_student_entry),
    path('add_first_entry', views.add_new_student_entry),
    path('edit_student_row', views.edit_student_row),
    path('update_paid_status', views.update_paid_status),
    path('update_received_status', views.update_received_books, name='update_received_status'),
    path('update_all_paid', views.update_all_paid),
    path('students_book', views.student_books, name='students_book'),
    path('delete_student_row', views.delete_student_row),
    path('<int:pk>/', views.student_detail, name='student_detail'),
]

students/models.py
from django.db import models
from books.models import Book

class Student(models.Model):
    name = models.CharField(max_length=100)
    year_group = models.CharField(max_length=20)
    paid_status = models.BooleanField(default=False)
    books_received = models.ManyToManyField('books.Book', through='BookReceived', related_name='students')

    def __str__(self):
        return self.name

class BookReceived(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    date_received = models.DateTimeField()

students/forms/forms.py
from django import forms

from students.models import BookReceived

class BookReceivedForm(forms.ModelForm):
    class Meta:
        model = BookReceived
        fields = ['student', 'book', 'date_received']

student/views.py
import os

import pandas
import pandas as pd
from django.http import FileResponse
from django.shortcuts import render, redirect, get_object_or_404
import json
from django.templatetags.static import static
from enasInventory.forms.student import SearchStudentForm, YearGroupFilterForm, StudentBookForm
from enasInventory.models import Student
from enasInventory.models import Book
from enasInventory.models import BookReceived
from datetime import datetime


def add_student_entry(request):
    if request.method == 'POST':
        print(request.POST)
        student_name = request.POST.get('student_name')
        year_group = request.POST.get('year_group')
        new_student = Student(name=student_name, year_group=year_group, paid_status=False)
        new_student.save()
    return redirect('students_book')


def student_books(request):
    search_form = SearchStudentForm(request.GET or None)
    filter_form = YearGroupFilterForm(request.GET or None)  # Instantiate the form with the submitted data, if any
    students = Student.objects.all()
    if filter_form.is_valid():
        year_group = filter_form.cleaned_data['year_group']
        students = Student.objects.all()

        if year_group:
            students = students.filter(year_group=year_group)

    if search_form.is_valid():
        print(search_form)
        search_query = search_form.cleaned_data['search_student_query']
        if search_query:
            students = students.filter(name__icontains=search_query)

    students_data = students.values()

    return render(request, 'students-book.html',
                  {'students_data': students_data, 'filter_form': filter_form, 'search_form': search_form})


def add_students_bulk(request):
    try:
        if request.FILES['student_inventory']:
            file = request.FILES['student_inventory']
            if file.name.endswith('.xlsx') or file.name.endswith('.xls'):
                excel_file = pd.ExcelFile(file)
                sheet_names = excel_file.sheet_names
                print(sheet_names)
                for sheet in sheet_names:
                    read_excel_file = pandas.read_excel(file, sheet)
                    for _, book in read_excel_file.iterrows():
                        saved_students = Student(
                            name=book['student_name'],
                            year_group=sheet,
                            paid_status=False
                        )
                        saved_students.save()
            return redirect('students_book')
    except Exception as e:
        print(str(e))
        return redirect('students_book')
    return redirect('students_book')


def edit_student_row(request):
    if request.method == 'POST':
        student_id = request.POST.get('student_id')
        student_name = request.POST.get('student_name')
        year_group = request.POST.get('year_group')
        Student.objects.filter(id=student_id).update(name=student_name, year_group=year_group)
    return redirect('students_book')


def update_paid_status(request):
    if request.method == 'POST':
        book_id = request.POST.get('student_id')
        Student.objects.filter(id=book_id).update(paid_status=True)
    return redirect('students_book')


def update_all_paid(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        student_ids = data['student_ids']
        for ids in student_ids:
            Student.objects.filter(id=ids).update(paid_status=True)
    return redirect('students_book')


def delete_student_row(request):
    if request.method == 'POST':
        student_id = request.POST.get('student_id')
        selected_student = Student.objects.get(id=student_id)
        selected_student.delete()
    return redirect('students_book')


def download_template(request):
    # Get the file path of the template Excel file using the static() helper function
    template_file_path = os.path.join(static('excel_templates'), 'student_template.xlsx')

    # Open the file using FileResponse and set the appropriate content type
    response = FileResponse(open(template_file_path, 'rb'),
                            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    # Set the Content-Disposition header to force download with the original filename
    response['Content-Disposition'] = 'attachment; filename="student_template.xlsx"'
    return response


def student_detail(request, pk):
    student = get_object_or_404(Student, pk=pk)
    student_year_group = student.year_group
    year_books = Book.objects.filter(year_group=student_year_group)
    received_books = BookReceived.objects.filter(student_id=pk)
    book_form = StudentBookForm(request.POST or None)
    if request.method == "POST":
        if book_form.is_valid():
            isbn = book_form.cleaned_data['isbn_name']
            book_name = book_form.cleaned_data['book_name']
            order_status = "REQUESTED"
            current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
            print(current_time)
            quantity_needed = 1
            quantity_received = 0
            new_book = Book(book_name=book_name, isbn=isbn, quantity_needed=quantity_needed,
                            quantity_received=quantity_received,
                            year_group=student_year_group, order_status=order_status, date_requested=current_time)
            new_book.save()

    return render(request, 'student_detail.html', {'student': student, 'books': year_books, 'book_form': book_form, 'received_books': received_books})

students/views.py
import os

import pandas
import pandas as pd
from django.db.models import Q
from django.http import FileResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
import json
from django.templatetags.static import static
from enasInventory.forms.forms import SearchStudentForm, YearGroupFilterForm, StudentBookForm, \
    PaidStatusFiltering
from students.forms.forms import BookReceivedForm
from students.models import Student
from books.models import Book
from django.utils import timezone
from datetime import datetime
from django.db import IntegrityError


def add_student_entry(request):
    if request.method == 'POST':
        student_name = request.POST.get('student_name')
        year_group = request.POST.get('year_group')
        try:
            new_student = Student(name=student_name, year_group=year_group, paid_status=False)
            new_student.save()
            return redirect('students:students_book')
        except IntegrityError:
            # Handle the IntegrityError if needed
            pass

    # Handle other cases or display an error message
    return HttpResponse("Error occurred while adding a student.")


def add_new_student_entry(request):
    if request.method == 'POST':
        student_name = request.POST.get('student_name')
        year_group = request.POST.get('year_group')
        paid_status = request.POST.get('paid_status')
        if paid_status == 'True':
            paid_status = True
        else:
            paid_status = False
        new_student = Student(name=student_name, year_group=year_group, paid_status=paid_status)
        new_student.save()
        return redirect('students:students_book')


def student_books(request):
    search_form = SearchStudentForm(request.GET or None)
    filter_form = YearGroupFilterForm(request.GET or None)  # Instantiate the form with the submitted data, if any
    paid_status = PaidStatusFiltering(request.GET or None)
    students = Student.objects.all()
    if filter_form.is_valid():
        year_group = filter_form.cleaned_data['year_group']
        students = Student.objects.all()
        if year_group:
            students = students.filter(year_group=year_group)
    if search_form.is_valid():
        print(search_form)
        search_query = search_form.cleaned_data['search_student_query']
        if search_query:
            students = students.filter(name__icontains=search_query)
    if paid_status.is_valid():
        paid_status_query = paid_status.cleaned_data['paid_status']
        if paid_status_query:
            students = students.filter(paid_status=paid_status_query)
    students_data = students.values()

    return render(request, 'students-book.html',
                  {'students_data': students_data, 'filter_form': filter_form, 'search_form': search_form,
                   'paid_filter': paid_status})


def add_students_bulk(request):
    try:
        if request.FILES['student_inventory']:
            file = request.FILES['student_inventory']
            if file.name.endswith('.xlsx') or file.name.endswith('.xls'):
                excel_file = pd.ExcelFile(file)
                sheet_names = excel_file.sheet_names
                print(sheet_names)
                for sheet in sheet_names:
                    read_excel_file = pandas.read_excel(file, sheet)
                    for _, book in read_excel_file.iterrows():
                        saved_students = Student(
                            name=book['student_name'],
                            year_group=sheet,
                            paid_status=False
                        )
                        saved_students.save()
            return redirect('students_book')
    except Exception as e:
        print(str(e))
        return redirect('students:students_book')
    return redirect('students:students_book')


def edit_student_row(request):
    if request.method == 'POST':
        student_id = request.POST.get('student_id')
        student_name = request.POST.get('student_name')
        year_group = request.POST.get('year_group')
        Student.objects.filter(id=student_id).update(name=student_name, year_group=year_group)
    return redirect('students:students_book')


def update_paid_status(request):
    if request.method == 'POST':
        book_id = request.POST.get('student_id')
        Student.objects.filter(id=book_id).update(paid_status=True)
    return redirect('students:students_book')


def update_all_paid(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        student_ids = data['student_ids']
        for ids in student_ids:
            Student.objects.filter(id=ids).update(paid_status=True)
    return redirect('students:students_book')


def delete_student_row(request):
    if request.method == 'POST':
        student_id = request.POST.get('student_id')
        selected_student = Student.objects.get(id=student_id)
        selected_student.delete()
    return redirect('students:students_book')


def download_template(request):
    # Get the file path of the template Excel file using the static() helper function
    template_file_path = os.path.join(static('excel_templates'), 'student_template.xlsx')

    # Open the file using FileResponse and set the appropriate content type
    response = FileResponse(open(template_file_path, 'rb'),
                            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    # Set the Content-Disposition header to force download with the original filename
    response['Content-Disposition'] = 'attachment; filename="student_template.xlsx"'
    return response


def student_detail(request, pk):
    student = get_object_or_404(Student, pk=pk)
    student_year_group = student.year_group
    year_books = Book.objects.filter(year_group=student_year_group)
    received_books = BookReceived.objects.filter(student=student)
    received_books_list = list(received_books.values_list('book_id', flat=True))
    not_received_books = year_books.exclude(id__in=received_books_list)
    book_form = StudentBookForm(request.POST or None)

    if request.method == "POST":
        if book_form.is_valid():
            isbn = book_form.cleaned_data['isbn_name']
            book_name = book_form.cleaned_data['book_name']
            order_status = "REQUESTED"
            current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
            quantity_needed = 1
            quantity_received = 0
            new_book = Book(book_name=book_name, isbn=isbn, quantity_needed=quantity_needed,
                            quantity_received=quantity_received,
                            year_group=student_year_group, order_status=order_status, date_requested=current_time)
            new_book.save()
    return render(request, 'student_detail.html',
                  {
                      'student': student,
                      'books': year_books,
                      'book_form': book_form,
                      'received_books': received_books,
                      'not_received_books': not_received_books,
                  })


def update_received_books(request):
    student_id = request.POST.get('student_id')
    book_id = request.POST.get('book_id')
    already_received = BookReceived.objects.filter(book_id=book_id, student_id=student_id)
    if not already_received:
        date_received = timezone.now()
        new_received_book = BookReceived(book_id=book_id, student_id=student_id, date_received=date_received)
        new_received_book.save()
        return redirect('students:student_detail', student_id)
    else:
        print('Already done')

        # print('The following has already been received' + already_received[0])

students/templates/student_detail.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <script src = "{% static 'javascript/student-index.js' %}" defer></script>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&display=swap">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>

</head>
<body>
{% include "header.html" %}
  <div class="shift_left">
    <h3>Student Books Detail</h1>
    <p>Name: {{ student.name }}</p>
    <p>Year Group: {{ student.year_group }}</p>
     {% if books %}
         <table>
          <thead>
                    <th>Book Name</th>
                    <th>Received</th>
                    <th>Date Received</th>
                    <th>Actions</th>
                  </thead>
           {% for book_received in received_books %}
              <tr>
                <td>{{ book_received.book.book_name }}</td>
                <td>Yes</td>
                <td>{{ book_received.date_received }}</td>
              <td>
                <div class="align-button">
                  <span class="material-symbols-outlined circle_check">
                    check_circle
                    </span>
                    Book received
                </div>
                </td>
              </tr>
        {% endfor %}
          {% for not_received in not_received_books %}
              <tr>
                <td>{{ not_received.book_name }}</td>
                <td>No</td>
                <td>Not received</td>
              <td>
                        <button class="update_received_status button_style" data-book-id="{{ not_received.id }}" data-student-id="{{ student.id }}" data-url="{% url 'students:update_received_status' %}">
                          <div class="align-button">
                              Update Receive Status
                              <span class="material-symbols-outlined">
                                  update
                              </span>
                          </div>
                          </button>
                     </td>
              </tr>
        {% endfor %}
          </table>
          {% else %}
         <p>No books is available in the system for this year group.</p>
         <p>You can add a book for this year group and student by completing the form down below</p>
         <form method="post" class="form_align">
             {% csrf_token %}
             {{book_form.isbn_name.label_tag}}
             {{book_form.isbn_name|add_class:"textfield_mui"}}
             {{book_form.book_name.label_tag}}
             {{book_form.book_name}}
            <!--{{ book_form.as_table }}-->
            <button type="submit" class="button_style">
              <div class="align-button">
                  <span class="material-symbols-outlined">
                      add
                  </span>
                  Add book
              </div>
            </button>
         </form>
    {% endif %}
  </div>
    
</body>
</html>

students/templates/students-book.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <script src = "{% static 'javascript/student-index.js' %}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
</head>
<body>
{% include "header.html" %}
<div class="shift_left">
    <h3>Student Book Management</h3>
<div class="student-forms">
    <form method="get">
        {% csrf_token %}
        {{ filter_form.year_group.label_tag }}
        {{ filter_form.year_group|add_class:"mui_select" }}
    <button type="submit" class="button_style">
        <div class="align-button">
            Filter
            <span class="material-symbols-outlined">
                filter_alt
            </span>
        </div>
    </button>
</form>
        <form method="get">
          {% csrf_token %}
          {{paid_filter.paid_status.label_tag}}
          {{paid_filter.paid_status|add_class:"mui_select"}}
    <!--{{ paid_filter.as_table }}-->
    <button type="submit" class="button_style">
        <div class="align-button">
            Filter
            <span class="material-symbols-outlined">
                filter_alt
            </span>
        </div>
    </button>
</form>
    <form method="get"> 
        {% csrf_token %}
        {{search_form.search_student_query.label_tag}}
        {{search_form.search_student_query|add_class:"textfield_mui"}}
        <!--{{ search_form.as_table }}-->
        <button type="submit" class="button_style">
            <div class="align-button">
                <span class="material-symbols-outlined">
                    search
                </span>
                Search
            </div>
            </button>
    </form>
</div>
        <p>To bulk add the students, you can download and fill this Excel template by   <a href="{% static 'excel_templates/student_template.xlsx' %}">Downloading Student Template</a>
        and uploading it in by clicking "Choose File" down below:
        </p>
    <form method="post" action="/students/add_students_bulk" enctype="multipart/form-data" class="padding_bottom">
        {% csrf_token %}
        <label for="books_inventory">Import Student List from Excel Sheet:</label><br>
          <input type="file" name="student_inventory" id="student_inventory" required>
       <button type="submit" class="button_style" >
        <div class="align-button">
            <span class="material-symbols-outlined">
                add
                </span>
            <span class="material-symbols-outlined">
                library_books
            </span>
            Bulk Add Students
        </div>
    </button>
    </form>

       {% if not students_data %}
    <div>
        <p> To add a single student item, click the Add first student entry</p>
      <button id="add_student_entry">Add first student entry </button>
    </div>
     {% endif %}

<div class="student_table_container">
 {% if students_data %}
         <table id="student_table">
            <thead>
                <tr>
                    <th>
                        <label for="select_all">Select All:</label>
                        <input type="checkbox" id="select_all" onclick="toggleAllCheckboxes(this)" >
                    </th>
                    <th>Student Name</th>
                    <th>Paid Status</th>
                     <th>Year Group</th>
                    <th>
                        Actions
                        <button id="add_new_student" class="button_style">
                            <div class="align-button">
                                Add new Student
                                <span class="material-symbols-outlined">
                                    add
                                </span>
                            </div>
                        </button>
                        <button id="update_all_students" class="button_style">
                            <div class="align-button">
                                Update All
                                <span class="material-symbols-outlined">
                                    sync
                                </span>
                            </div>
                        </button>
                        <button id="delete_all_students" class="button_style">
                            <div class="align-button">
                                Delete
                                <span class="material-symbols-outlined">
                                    delete
                                </span>
                            </div>
                        </button>
                    </th>

                </tr>
            </thead>
            <tbody>
                {% for student in students_data %}
                <tr>
                     <td>
                        <input type="checkbox" name="students_check" value="{{ student.id }}" required>
                     </td>
                    <td class="editable_data">{{ student.name }}</td>
                    <td class="paid_status">{{ student.paid_status }}</td>
                    <td class="editable_data">{{ student.year_group }}</td>
                    <td>
                        <button class="student_edit button_style" data-student-id = {{student.id }}>
                            <div class="align-button">
                                <span class="material-symbols-outlined">
                                    edit
                                </span>
                                Edit
                            </div>
                            
                        </button>
                        <button class="student_save button_style" data-student-id = {{student.id }}>
                            <div class="align-button">
                                <span class="material-symbols-outlined">
                                    save
                                </span>
                                Save
                            </div>
                           
                        </button>
                        <button class="student_delete button_style" data-student-id = {{student.id }}>
                            <div class="align-button">
                                <span class="material-symbols-outlined">
                                    delete
                                </span>
                                Delete
                            </div>
                        </button>

                        <button class="update_paid_statu button_style" data-student-id = {{student.id }}>
                            <div class="align-button">
                                <span class="material-symbols-outlined">
                                        check
                                </span>
                                Update Paid Status
                            </div>
                            
                        </button>
                        <a href="{% url 'students:student_detail' student.id  %}" class="mui_link">View Book Details</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
    </table>
  {% else %}
        <p>No student data available.</p>
 {% endif %}
</div>
</div>




</body>
</html>